### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by proxer05** [laraib07/androfetch#1]
![Screenshot_20201201-213806_Pixel_Launcher](https://user-images.githubusercontent.com/62423996/100794603-16232f80-341e-11eb-8108-5f1dd1152c56.png)

**Comment by laraib07** [comment]
Use meslo nerd fonts.
In  termux we are limited to only one font at a time. I tried building [font cache]( https://powerline.readthedocs.io/en/latest/installation/linux.html#fonts-installation) in termux using fontconfig-utils but I dind't worked.

I am planning to add an option to enable/disable icons.

**Comment by laraib07** [comment]
Added option to disable icon.
