### ISSUE TITLE
Incorrect platform detecting

### ISSUE THREAD

**Issue by wowlikon** [laraib07/androfetch#7]
![Code_qU1VViuJ7q](https://github.com/laraib07/androfetch/assets/73490630/8c78c49f-eda8-4a0b-878d-4d85c9bad607)

**Comment by laraib07** [comment]
@wowlikon Please give more details and is this androfetch??

**Comment by wowlikon** [comment]
I installed it incorrectly and because of this an error occurred. because I tried to compile from source, but some library did not compile

**Comment by laraib07** [comment]
@wowlikon You are at the wrong repo. This repo belongs to Androfetch which is a bash script for termux.
